import { ActivityType, Profile } from "@/generated/prisma/client";
import { generateText, Output } from "ai";
import { createAIActivity } from "../activity/service";
import { LeadServiceError } from "../lead/service";
import {
  dbCreateLeadBrief,
  dbGetLastLeadBrief,
  dbGetLeadWithContext,
  dbGetNextReminder,
  dbGetRecentActivities,
} from "./db";
import { buildLeadBriefPrompt, validateLeadAccess } from "./helpers";
import { leadBriefSchema, SaveLeadBriefRequest } from "./schema";

export async function generateLeadBrief(leadId: string, user: Profile) {
  const lead = await dbGetLeadWithContext(leadId);
  if (!lead) {
    throw new LeadServiceError("Lead not found", 404);
  }

  if (!validateLeadAccess(lead.assignedTo?.id, { id: user.id, role: user.role })) {
    throw new LeadServiceError("Unauthorized", 403);
  }

  const [activities, nextReminder] = await Promise.all([
    dbGetRecentActivities(leadId),
    dbGetNextReminder(leadId),
  ]);

  const prompt = buildLeadBriefPrompt({
    leadContext: lead,
    recentActivities: activities,
    nextReminder,
  });

  // Vercel AI SDK call: prompt + schema -> typed, validated brief object.
  const { output } = await generateText({
    model: "deepseek/deepseek-v3.2-thinking",
    output: Output.object({ schema: leadBriefSchema }),
    prompt,
  });

  await createAIActivity({
    type: ActivityType.AI_LEAD_BRIEF_GENERATED,
    leadId,
    actorId: user.id,
    content: `Lead brief generated by ${user.name}`,
  });

  return output;
}

export async function saveLeadBrief(request: SaveLeadBriefRequest, user: Profile) {
  const lead = await dbGetLeadWithContext(request.leadId);
  if (!lead) {
    throw new LeadServiceError("Lead not found", 404);
  }

  if (!validateLeadAccess(lead.assignedTo?.id, { id: user.id, role: user.role })) {
    throw new LeadServiceError("Unauthorized", 403);
  }

  return dbCreateLeadBrief(request, user);
}

export async function getLastLeadBrief(leadId: string, user: Profile) {
  const lead = await dbGetLeadWithContext(leadId);
  if (!lead) {
    throw new LeadServiceError("Lead not found", 404);
  }

  if (!validateLeadAccess(lead.assignedTo?.id, { id: user.id, role: user.role })) {
    throw new LeadServiceError("Unauthorized", 403);
  }

  const row = await dbGetLastLeadBrief(leadId);
  return row ?? null;
}
