import { ActivityType, Profile } from "@/generated/prisma/client";
import {
  APICallError,
  LoadAPIKeyError,
  NoSuchModelError,
  TypeValidationError,
  generateText,
  Output,
} from "ai";
import type { CallOutcome } from "../activity";
import { createAIActivity } from "../activity/service";
import { LeadServiceError } from "../lead/service";
import {
  dbCreateLeadBrief,
  dbGetLastLeadBrief,
  dbGetLeadWithContext,
  dbGetNextReminder,
  dbGetRecentActivities,
} from "./db";
import {
  buildCallFollowupPrompt,
  buildLeadBriefPrompt,
  validateLeadAccess,
} from "./helpers";
import {
  callFollowUpSchema,
  type CallFollowUp,
  leadBriefSchema,
  type LeadBrief,
  SaveLeadBriefRequest,
} from "./schema";

export class AIServiceError extends Error {
  constructor(
    message: string,
    public statusCode: number,
  ) {
    super(message);
    this.name = "AIServiceError";
  }
}

function throwMappedAiError(error: unknown): never {
  if (LoadAPIKeyError.isInstance(error)) {
    throw new AIServiceError(
      "AI gateway key is missing or invalid. Set AI_GATEWAY_API_KEY in .env and restart the dev server.",
      503,
    );
  }
  if (APICallError.isInstance(error)) {
    const status = error.statusCode;
    const body =
      typeof error.responseBody === "string"
        ? error.responseBody.slice(0, 800)
        : undefined;
    const message =
      body?.trim() || error.message || "AI gateway request failed";

    if (status === 401 || status === 403) {
      throw new AIServiceError(
        "AI gateway rejected the API key. Regenerate the key in Vercel (AI Gateway → API keys) and update AI_GATEWAY_API_KEY.",
        status,
      );
    }
    if (status === 429) {
      throw new AIServiceError(
        "AI gateway rate limit exceeded. Try again in a minute.",
        429,
      );
    }
    throw new AIServiceError(message, 502);
  }
  if (NoSuchModelError.isInstance(error)) {
    throw new AIServiceError(error.message, 400);
  }
  if (TypeValidationError.isInstance(error)) {
    throw new AIServiceError(
      `Model output did not match the expected shape: ${error.message}`,
      422,
    );
  }
  if (error instanceof Error) {
    throw new AIServiceError(error.message, 500);
  }
  throw new AIServiceError("AI generation failed", 500);
}

export async function generateLeadBrief(leadId: string, user: Profile) {
  const lead = await dbGetLeadWithContext(leadId);
  if (!lead) {
    throw new LeadServiceError("Lead not found", 404);
  }

  if (!validateLeadAccess(lead.assignedTo?.id, { id: user.id, role: user.role })) {
    throw new LeadServiceError("Unauthorized", 403);
  }

  const [activities, nextReminder] = await Promise.all([
    dbGetRecentActivities(leadId),
    dbGetNextReminder(leadId),
  ]);

  const prompt = buildLeadBriefPrompt({
    leadContext: lead,
    recentActivities: activities,
    nextReminder,
  });

  let output: LeadBrief;
  try {
    const result = await generateText({
      model: "deepseek/deepseek-v3.2-thinking",
      output: Output.object({ schema: leadBriefSchema }),
      prompt,
    });
    output = result.output;
  } catch (error) {
    throwMappedAiError(error);
  }

  const activityResult = await createAIActivity({
    type: ActivityType.AI_LEAD_BRIEF_GENERATED,
    leadId,
    actorId: user.id,
    content: `Lead brief generated by ${user.name}`,
  });
  if (!activityResult.success) {
    throw new AIServiceError(
      `Failed to log activity: ${JSON.stringify(activityResult.errors)}`,
      500,
    );
  }

  return output;
}

export async function saveLeadBrief(request: SaveLeadBriefRequest, user: Profile) {
  const lead = await dbGetLeadWithContext(request.leadId);
  if (!lead) {
    throw new LeadServiceError("Lead not found", 404);
  }

  if (!validateLeadAccess(lead.assignedTo?.id, { id: user.id, role: user.role })) {
    throw new LeadServiceError("Unauthorized", 403);
  }

  return dbCreateLeadBrief(request, user);
}

export async function getLastLeadBrief(leadId: string, user: Profile) {
  const lead = await dbGetLeadWithContext(leadId);
  if (!lead) {
    throw new LeadServiceError("Lead not found", 404);
  }

  if (!validateLeadAccess(lead.assignedTo?.id, { id: user.id, role: user.role })) {
    throw new LeadServiceError("Unauthorized", 403);
  }

  const row = await dbGetLastLeadBrief(leadId);
  return row ?? null;
}

export async function generateCallFollowup(
  leadId: string,
  callOutcome: CallOutcome,
  agentNotes: string | undefined,
  user: Profile,
) {
  const lead = await dbGetLeadWithContext(leadId);
  if (!lead) {
    throw new LeadServiceError("Lead not found", 404);
  }

  if (!validateLeadAccess(lead.assignedTo?.id, { id: user.id, role: user.role })) {
    throw new LeadServiceError("Unauthorized", 403);
  }

  const activities = await dbGetRecentActivities(leadId, 10);

  const prompt = buildCallFollowupPrompt({
    leadContext: lead,
    recentActivities: activities,
    callOutcome,
    agentNotes,
  });

  let output: CallFollowUp;
  try {
    const result = await generateText({
      model: "deepseek/deepseek-v3.2-thinking",
      output: Output.object({ schema: callFollowUpSchema }),
      prompt,
    });
    output = result.output;
  } catch (error) {
    throwMappedAiError(error);
  }

  return output;
}
